version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pulsenode-db
    restart: always
    environment:
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_password
      POSTGRES_DB: pulsenode_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse_user -d pulsenode_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
